name: Databricks CI (unit test)

on:
    push:
        branches:
            - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            
            - name: Install dependency
              run: pip install pyspark pytest

            - name: Run Unit Tests
              run: pytest tests/